### ISSUE TITLE
Add link for user to sign out so they can pick a different Azure AD account

### ISSUE THREAD

**Issue by skwan** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#1]
This is different than signing out of the app.  After doing the OAuth flow to see a particular user profile, the user might want to pick a different profile.  But they can't do this from the app because there is only an affordance to sign out of the app, which leaves them signed in to Azure AD.  Add a way to send a sign out request to Azure AD from the profile page.

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
