### ISSUE TITLE
Can you provide the same sample in python

### ISSUE THREAD

**Issue by manikarthikk** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#10]

**Comment by TiagoBrenck** [comment]
Python sample: https://github.com/Azure-Samples/ms-identity-python-webapp

Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
