### ISSUE TITLE
Still maintaining this project?

### ISSUE THREAD

**Issue by wgoulet** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#11]
Hi,

I forked this repo as the basis for another project and was curious if this was still being actively maintained. If so, some of my changes may be interesting for you to pull.

Thanks,
Walter

**Comment by jmprieur** [comment]
@wgoulet : feel free to provide a PR if this does not give you too much work.

**Comment by kalyankrishna1** [comment]
Yes, its still being maintained
