### ISSUE TITLE
Can you provide the same sample in Web API

### ISSUE THREAD

**Issue by largeDachshund** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#14]
This Sample has .Net MVC muddled in it.  If you're running  a RESTful API, there's no front-end.  I'd love to see a MSFT-approved method for Web API auth.  Please, build this with Web API, alone.

Thanks,

**Comment by jmprieur** [comment]
@largeDachshund : does this sample work for you; https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2 ?

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
