### ISSUE TITLE
Getting profile: server error - Value cannot be null. Parameter name: clientSecret

### ISSUE THREAD

**Issue by mvancamp** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#16]
In the downloaded zip example there is still a small error in the Web.config file.
In the appsettings the key "ida:AppKey" is used for the client secret, whereas in the Startup.Auth.cs code a search is done against the "ida:ClientSecret" key.  By changing the Web.config file accordingly the error is solved:

`<add key="ida:ClientSecret" value="[The client secret saved from the Azure Portal Certificates & Secrets section]" />`

All other stuff is working well! Thanks for the example.

**Comment by TiagoBrenck** [comment]
Hi @mvancamp, thanks for catching that.
