### ISSUE TITLE
AD integration not working anymore?

### ISSUE THREAD

**Issue by bensgroi** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#5]
The AD integration doesn't appear to be working anymore. The redirect back to the site after Azure sign-in doesn't pass a "state" parameter to the Index action on the OAuthController. This results in an error. It does pass a "session_state" value, but it appears to be a guid, and "state" needs to be a base 64 encoded string. Maybe AD's return parameters have changed since this project was written?

**Comment by kalyankrishna1** [comment]
The sample has been rewritten completely, please give it a try again let us know if you still face an issue

**Comment by bensgroi** [comment]
I'm no longer working on that project, so this isn't something I can currently test. But thanks for responding.
