### ISSUE TITLE
Make this work with WS-Federation

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#6]
I'm trying to integrate this with WS-Federation instead of OAuth but couldn't. Not able to receive authorization code and also TokenCache code gives me server timeout 500 error. Thanks for your help!

**Comment by kalyankrishna1** [comment]
Please expand your question with more details. what IdP are you using for WS-Fed. What changes did you make?

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API
