### ISSUE TITLE
Going to /UserProfile after signing-in causes error

### ISSUE THREAD

**Issue by RyanTaite** [Azure-Samples/AzureAD-WebApp-WebAPI-OAuth2-UserIdentity-DotNet#9]
After signing-in into a local account, navigating to https://localhost:44323/UserProfile produces this error:

    Server Error in '/' Application.`
    Invalid object name 'dbo.TokenCacheEntries'.
    ...
    Line 24:
    Line 25:             // look up the entry in the DB
    Line 26:             Cache = db.TokenCacheEntries.FirstOrDefault(c => c.userObjId == userObjId);
    Line 27:             // place the entry in memory
    Line 28:             this.Deserialize((Cache == null) ? null : Cache.cacheBits);
    --
    Source File: C:\Users\...\Documents\Visual Studio 2017\Projects\adal-graph\WebApp\Models\TokenDbCache.cs    Line: 26

**Comment by gsacavdm** [comment]
Looks like your database does not have the TokenCacheEntries table...

**Comment by RyanTaite** [comment]
Looks like I figured it out by taking hints from this similar issue: https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-useridentity/issues/4

I should point out that I'm using Visual Studio 2017, in case it affects anything.

**Steps taken:**

1. Downloaded sample project, and opened it in VS 2017
2. Followed `Step 2: Register the sample with your Azure Active Directory tenant` and `Step 3: Configure the sample to use your Azure AD tenant` with the only difference being I named my app differently
3. In the Azure AD App Settings area, in the Reply URLs I added `https://localhost:44323/OAuth`
    - Without this I got an error when signing into my AAD account on the /UserProfile page
    - This step is not (at the time of writing this) mentioned in the walkthrough steps.
4. In the project, in Package Manager Console I restored the missing references
5. Again in the Package Manager Console I type:
`Enable-Migrations`
`Add-Migration initial-migration`
`Update-Database`
    - This was needed to create the TokenCacheEntries table

I'm now able to run the app, register as a local user, proceed to navigate to the User Profile page, and sign into AAD.

**Comment by kalyankrishna1** [comment]
The sample has been rewritten completely, please give it a try again let us know if you still face an issue

**Comment by RyanTaite** [comment]
It's been a while, so I'm guessing the original page is this one: https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-webapi-oauth2-useridentity/

I'm using Visual Studio Professional 2017 v15.9.6, I use Firefox 64-bit v65.0 as my browser to launch this in.

1. A link near the start of Step 2 leading to "App Creation Scripts" is broken: https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-webapi-oauth2-useridentity/appcreationscripts/appcreationscripts.md
2. In the "Register the service app (OAuth2-UserIdentity)" section, in step 2, it asks us to enter two URLs but there is only one box (doesn't seem to be a combo box as described) with no description of how to add more:

    ![registeranapplicationredirecturl](https://user-images.githubusercontent.com/5490996/52428047-1770c300-2af9-11e9-892c-eddedd1ea73a.PNG)

    2.a Looks like I can add more once I'm on the Authentication page during Step 5 of the same section, so I would suggest moving this part of Step 2 into Step 5

3. There is a space missing between "flow" and "to" in this sentence: "the Implicit grant flowto be enabled"

4. In "Configure the service project" it might help to clarify that "AppKey" is the same as the secret generated earlier, and that you can get the Tenant Id from the Overview page of the App Registration.

5. Able to clean and rebuild the app with no errors, but once loaded it sends me to an error page saying "Server Error in '/' Application.
Could not find a part of the path 'C:\removed\Desktop\ADOauth2Test\active-directory-dotnet-webapp-webapi-oauth2-useridentity\OAuth2-UserIdentity\bin\roslyn\csc.exe'. ":
    ![servererror](https://user-images.githubusercontent.com/5490996/52431406-14c59c00-2b00-11e9-9450-020e4ce8d258.PNG)


That's as far as I've gotten.

_Edit: Typos_

**Comment by kalyankrishna1** [comment]
Thanks for taking the time to review this. To get rid of the roslyn error

Could not find a part of the path … bin\roslyn\csc.exe

Please open the Nuget package manage window (View->Other windows->Package Manager Console
and execute the following command

Uninstall-package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

We're incorporating the rest of your suggestions as well

**Comment by RyanTaite** [comment]
Uninstalling that package did the trick and I'm now able to move forward with the tutorial:

- In the `Create and publish the OAuth2-UserIdentity to an Azure Web Site` section:
    - Step 2, it asks me to click `Web + Mobile --> Web App`, currently there is no `Web + Mobile` option. There is both `Web` and `Mobile` though, as separate choices:
        ![webandmobile](https://user-images.githubusercontent.com/5490996/52575060-75f9b200-2e15-11e9-85c6-88ae16576f06.PNG)
        - Clicking on `Web` will get you to the `Web App` option
    - Step 3, it asks to click `"Create a new database"`, looks like the wording has changed to `Add`. Similar for `DB Connection String Name`, changed to `Database name`
    - Step 7, "Settings" has changed to "Configure"
- In the `Update the Active Directory tenant application registration for OAuth2-UserIdentity` section:
    - Step 2, not positive but I think the "Directory list" has been moved behind the "Switch directory" link
    - Step 3, I _think_ the "applications tab" has been changed to "App Services"
    - Step 4, unsure where the `Settings` page is for my Application in Azure since the `Settings` section -> `Application settings` does not contain a way for me to change my logout URL
        - Looks like this is supposed to be in `Azure Active Directory` -> `App registrations (Preview)` (Normal doesn't show my app at all) -> Click on my app -> Under `Manage` click `Authentication`
        - It's here I'm able to update the Logout URL
    - Step 5, following the Step 4 changes move from `Authentication` to `Branding` and add the `Home page URL`
    - Step 6, move back to the `Authentication` and add the URL to the `Redirect URIs` (changed from "Reply URLs", though still referenced as such in the manifest as `replyUrlsWithType`)

After doing all this I go and test the app following the same steps listed in `Step 4: Run the sample`, but I just get the generic `An error occurred while processing your request.` message when loading any page that makes a call to the database (Submitting a registration, logging in)

I think this is because of some missteps around Section `Create and publish the OAuth2-UserIdentity to an Azure Web Site` Step 3.

Pretty sure the intended result is to update the Connection String in the App Service page -> `Settings` section -> `Application Settings` (`Configuration (Preview)` looks to be replacing this in the future) -> `Connection Strings` section -> Add new Connection String with a name of `DefaultConnection` (instead of actually naming the Database `DefaultConnection`) and a value of the SQL Database created for this tutorial with the username and password edited in.

**Comment by jmprieur** [comment]
@kalyankrishna1 : may I let you handle this one?

**Comment by kalyankrishna1** [comment]
yes, PR with fixes out for review

**Comment by kalyankrishna1** [comment]
The steps to deploy on Azure has been updated again. Thanks for your patience.

**Comment by kalyankrishna1** [comment]
Closing this as the user hasn't responded
